version: '3'
services:
  api:
    build: .
    environment:
      APP_ENV: "local"
    ports:
      - "8001:8001"
  postgres:
    image: "postgres:12.3"
    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_USER: "go_user"
      POSTGRES_DB: "gorm"